language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install coveralls
script: coverage run --source mcrunner setup.py test
after_success:
  coveralls
